In [1]:
import pandas as pd
import numpy as np
import tkinter as tk
from tkinter import simpledialog 

In [2]:
#Load your Excel file into a pandas DataFrame
excel_file = pd.read_csv(r'E:\Concordia University\Term 4\Capestone\Test code\excel.csv')

# Extract the column names as criteria
criteria = excel_file.columns.tolist()

In [3]:
# Create a function to input pairwise comparisons using a Tkinter dialog
def input_comparison(i, j):
    root = tk.Tk()
    root.withdraw()
    value = simpledialog.askfloat(f"Compare {criteria[i]} and {criteria[j]}", "Enter the comparison value (1 for equal importance, 3 for moderate importance, 5 for strong importance, and so on):")
    root.destroy()
    return value

# Create a dictionary to store user choices (yes/no) for each column
column_choices = {}

# Ask the user for column choices (yes or no)
for col in criteria:
    choice = input(f"Do you want to consider the column '{col}' for pairwise comparison? (yes/no)(just type y/n): ")
    if choice.lower() == "y":
        column_choices[col] = True
    else:
        column_choices[col] = False

def create_pairwise_matrix(criteria, choices):
    n = len(criteria)
    matrix = np.ones((n, n))

    for i in range(n):
        for j in range(i + 1, n):
            if choices[criteria[i]] and choices[criteria[j]]:
                value = input_comparison(i, j)
                matrix[i][j] = value
                matrix[j][i] = 1.0 / value

    return matrix





Do you want to consider the column 'Vendor' for pairwise comparison? (yes/no)(just type y/n): y
Do you want to consider the column 'cost(cad)' for pairwise comparison? (yes/no)(just type y/n): y
Do you want to consider the column 'Review rating(5)' for pairwise comparison? (yes/no)(just type y/n): y
Do you want to consider the column 'distance(KM)' for pairwise comparison? (yes/no)(just type y/n): n
Do you want to consider the column 'Quality' for pairwise comparison? (yes/no)(just type y/n): n
Do you want to consider the column 'Environmental' for pairwise comparison? (yes/no)(just type y/n): n


In [4]:
# Example usage:
pairwise_matrix = create_pairwise_matrix(criteria, column_choices)

# Print the pairwise comparison matrix
print("Pairwise Comparison Matrix:")
for i in range(len(pairwise_matrix)):
    print(" ".join([f"{value:.2f}" for value in pairwise_matrix[i]]))

# The rest of your code for normalization, criteria weights
normalized_matrix = pairwise_matrix / pairwise_matrix.sum(axis=0)# method 3 for eigenvector
criteria_weights = normalized_matrix.mean(axis=1)
n = len(criteria_weights)
eigenvalue, eigenvector = np.linalg.eig(pairwise_matrix)
max_eigenvalue = max(eigenvalue)
consistency_index = (max_eigenvalue - n) / (n - 1)
random_index = {
    1: 0.00,
    2: 0.00,
    3: 0.58,
    4: 0.90,
    5: 1.12,
    6: 1.24,
    7: 1.32,
    8: 1.41,
    9: 1.45,
    10: 1.49
}
consistency_ratio = consistency_index / random_index[n]

# Print the results
print("Normalized Pairwise Comparison Matrix:")
print(normalized_matrix)
print("\nCriteria Weights:")
for i, weight in enumerate(criteria_weights):
    print(f"{criteria[i]}: {weight:.3f}")
print("\nConsistency Ratio (CR):", consistency_ratio)


if consistency_ratio < 0.1:
    print("The matrix is consistent.")
else:
    print("The matrix is inconsistent.")


Pairwise Comparison Matrix:
1.00 3.00 1.00 1.00 1.00 1.00
0.33 1.00 5.00 1.00 1.00 1.00
1.00 0.20 1.00 1.00 1.00 1.00
1.00 1.00 1.00 1.00 1.00 1.00
1.00 1.00 1.00 1.00 1.00 1.00
1.00 1.00 1.00 1.00 1.00 1.00
Normalized Pairwise Comparison Matrix:
[[0.1875     0.41666667 0.1        0.16666667 0.16666667 0.16666667]
 [0.0625     0.13888889 0.5        0.16666667 0.16666667 0.16666667]
 [0.1875     0.02777778 0.1        0.16666667 0.16666667 0.16666667]
 [0.1875     0.13888889 0.1        0.16666667 0.16666667 0.16666667]
 [0.1875     0.13888889 0.1        0.16666667 0.16666667 0.16666667]
 [0.1875     0.13888889 0.1        0.16666667 0.16666667 0.16666667]]

Criteria Weights:
Vendor: 0.201
cost(cad): 0.200
Review rating(5): 0.136
distance(KM): 0.154
Quality: 0.154
Environmental: 0.154

Consistency Ratio (CR): (0.09843223568745814+0j)
The matrix is consistent.
